services:
  web-server:
    build:
      context: .
      dockerfile: ./web-server/Dockerfile
    container_name: webserver
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot/:ro
    ports:
      - "80:80"
      - "443:443"

